from sqlalchemy import Column, Integer, String, ForeignKey, JSON, Float, DateTime
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.core.database import Base

class Job(Base):
    __tablename__ = "jobs"

    # We use a String for ID to accommodate UUIDs generated by the API
    id = Column(String, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    
    # Lifecycle: pending -> running -> completed -> failed
    status = Column(String, default="pending")
    current_stage = Column(String, default="QUEUED")
    
    # Input Data
    file_name = Column(String, nullable=False)
    target_chain = Column(String, nullable=False)
    binder_chain = Column(String, nullable=False)
    
    # Physics Results (The Verdict)
    # Stored as JSON to capture the full 'Three-Tier Sieve' output
    verdict = Column(String, nullable=True) # PASS, VETO, METASTABLE
    
    # Metrics: rho_pre, rho_post, retention, clashes, min_dist
    metrics = Column(JSON, nullable=True)
    
    # Error tracking
    error_log = Column(String, nullable=True)
    
    # Timing
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)

    # Relationship back to the User
    owner = relationship("User", backref="jobs")

    def __repr__(self):
        return f"<Job(id={self.id}, status={self.status}, verdict={self.verdict})>"
